### PR TITLE
Add monitoring functionality

### PR DESCRIPTION
**Pull request by wfarah**
Add functionality to grab (hdr+data) ringbuffer stats,
the same way `dada_dbmonitor` would do
Not sure if the method name is the best, I'll leave it to the authors to decide

### CODE REVIEW

**Review by jiskattema — APPROVED** [review]

**Comment by jiskattema** [comment]
Thanks for you contributions, i hope the code is useful.
Can you add documentation for the statistics function? or add an example?

**Comment by wfarah** [comment]
Sure thing. Can you please advise on which file I need to edit for documentation?


Also, from a code design perspective, the parent `Ringbuffer` class is not directly accessible to the user (i.e. not in `psrdada`'s `__init__.py`). In principle, to just monitor a ringbuffer, we do not explicitly need a `Reader` nor a `Writer` object, as we are not consuming/processing data. If you are O.K. with this, I might just add a `from psrdada.ringbuffer import Ringbuffer` to the module's `__init__.py` file.

**Comment by jiskattema** [comment]
We use sphinx for the documentation. sphinx gets most of its info from the python doc strings. See the 'documentation' folder for the sphinx config etc. You can try it by running 'make html'

**Comment by jiskattema** [comment]
Note that we also have:
* make test : to run some basic test
* make check : to run some code quality checks (should be all ok ;) )

**Comment by jiskattema** [comment]
about the ringbuffer class and monitoring:
* A reader locks the ringbuffer for reading, so pages do not get reused until all readers have read them.
* A writer locks the ringbuffer for writing, and is also different from just observing.
* psrdada has a dada_hdu_open_view function specifically for observing

so i suggest you define a new class, Observer, that inherits from the ringbuffer just like Reader and Writer do, and connects with something like dada_hdu_open_view

**Comment by wfarah** [comment]
Okay, all the above is implemented. I will create a new pull request

**Comment by jiskattema** [comment]
Thanks for the commits; feel free to add yourself to the 'Authors' in the README.

**Comment by wfarah** [comment]
Sure thing, thanks!

**Pull request merged**
